'use strict';

/**
 * @type {Object<AttributeDefinition>}
 */
const attributes = {
    danger: {
        title: 'Danger',
        icon: 'img/icons/danger.svg',
        textClass: 'text-danger',
        relevantForMusicContext: false,
        getValue: () => Effect.getTotalValue( [EffectType.Danger, EffectType.DangerFactor]),
    },
    data: {
        title: 'Data',
        icon: 'img/icons/data.svg',
        textClass: 'text-data',
        relevantForMusicContext: false,
        getValue: () => gameData.data,
    },
    energy: {
        title: 'Energy',
        icon: 'img/icons/energy.svg',
        textClass: 'text-energy',
        relevantForMusicContext: false,
        getValue: () => Effect.getTotalValue( [EffectType.Energy, EffectType.EnergyFactor]),
    },
    essenceOfUnknown: {
        title: 'Essence of Unknown',
        icon: 'img/icons/essence-of-unknown.svg',
        textClass: 'text-essence-of-unknown',
        relevantForMusicContext: false,
        getValue: () => gameData.essenceOfUnknown,
    },
    gridLoad: {
        title: 'Grid Load',
        icon: 'img/icons/grid.svg',
        textClass: 'text-grid-load',
        relevantForMusicContext: false,
        getValue: () => calculateGridLoad(),
    },
    gridStrength: {
        title: 'Grid Strength',
        icon: 'img/icons/grid.svg',
        textClass: 'text-grid-strength',
        relevantForMusicContext: false,
        getValue: () => gridStrength.getGridStrength(),
    },
    growth: {
        title: 'Growth',
        icon: 'img/icons/growth.svg',
        textClass: 'text-growth',
        relevantForMusicContext: true,
        getValue: () => Effect.getTotalValue([EffectType.Growth, EffectType.GrowthFactor]),
    },
    industry: {
        title: 'Industry',
        icon: 'img/icons/industry.svg',
        textClass: 'text-industry',
        relevantForMusicContext: true,
        getValue: () => Effect.getTotalValue([EffectType.Industry, EffectType.IndustryFactor]),
    },
    military: {
        title: 'Military',
        icon: 'img/icons/military.svg',
        textClass: 'text-military',
        relevantForMusicContext: true,
        getValue: () => Effect.getTotalValue([EffectType.Military, EffectType.MilitaryFactor]),
    },
    population: {
        title: 'Population',
        icon: 'img/icons/population.svg',
        textClass: 'text-population',
        relevantForMusicContext: false,
        getValue: () => gameData.population,
    },
    research: {
        title: 'Research',
        icon: 'img/icons/research.svg',
        textClass: 'text-research',
        relevantForMusicContext: true,
        getValue: () => Effect.getTotalValue([EffectType.Research, EffectType.ResearchFactor]),
    },
};

/**
 * Define the descriptions of attributes, referencing each other.
 */
function createAttributeDescriptions() {
    attributes.danger.description = 'Drains ' +  attributes.population.inlineHtml + ' by that amount each cycle.';
    attributes.data.description = 'Invest to unlock <b>Technologies</b>. Generated by the <b>Analysis Core</b>.';
    attributes.gridLoad.description = 'Amount of ' + attributes.gridStrength.inlineHtml + ' currently assigned.';
    attributes.gridStrength.description = 'Limits the number of concurrently active Module Operations.';
    attributes.growth.description = 'Increases ' + attributes.population.inlineHtml + ' per cycle.<br />' +
        'Impact is enhanced while no Battle is engaged and ' + attributes.population.inlineHtml + ' has been higher before.';
    attributes.industry.description = 'Speeds up Module Operations progress.';
    attributes.military.description = 'Increases damage in Battles.';
    // TODO add analysis core in here, once done
    attributes.population.description = 'Speeds up Module Operations and Analysis Core progress and increases damage in Battles.';
    attributes.research.description = 'Speeds up Analysis Core progress, to generate ' + attributes.data.inlineHtml + ' for unlocking Technologies.';
    attributes.essenceOfUnknown.description = 'Invest to learn <b>Galactic Secrets</b>.';
}

/**
 *
 * @return {string}
 */
function createGridStrengthAndLoadDescription() {
    return `Each active module needs ${attributes.gridLoad.inlineHtmlWithIcon} but you can't use more than your 
    ${attributes.gridStrength.inlineHtmlWithIcon}. Try deactivating modules to free up the energy grid!`;
}

const gridStrength = new GridStrength({
    name:'GridStrength',
    title: 'Grid Strength',
    maxXp: 500,
    getMaxXp: (currentLevel, baseMaxXp) => {
        return Math.round(baseMaxXp * (currentLevel + 1) * Math.pow(1.6, currentLevel));
    }
});

const analysisCore = new AnalysisCore({
    name: 'AnalysisCore',
    title: 'Analysis Core',
    maxXp: 200,
    getMaxXp: function(currentLevel, baseMaxXp) {
        const exponentCap = 150;
        const exponentLimit = 170;
        return Math.round(baseMaxXp * (currentLevel + 1) * Math.pow(1.158, exponentCap * Math.tanh(currentLevel / exponentLimit)));
    }
});
